### ISSUE TITLE
Loading Mini Cheetah description in Pinocchio 2.6.10

### ISSUE THREAD

**Issue by stephane-caron** [robot-descriptions/robot_descriptions.py#15]
The URDF does not load with Pinocchio 2.6.10:

```
$ python examples/load_in_pinocchio.py mini_cheetah_description
Traceback (most recent call last):
  File "examples/load_in_pinocchio.py", line 35, in <module>
    robot = load_robot_description(args.name)
  File "~/.local/lib/python3.8/site-packages/robot_descriptions/loaders/pinocchio.py", line 69, in load_robot_description
    robot = pin.RobotWrapper.BuildFromURDF(
  File "~/.local/lib/python3.8/site-packages/cmeel.prefix/lib/python3.8/site-packages/pinocchio/robot_wrapper.py", line 17, in BuildFromURDF
    robot.initFromURDF(filename, package_dirs, root_joint, verbose, meshLoader)
  File "~/.local/lib/python3.8/site-packages/cmeel.prefix/lib/python3.8/site-packages/pinocchio/robot_wrapper.py", line 21, in initFromURDF
    model, collision_model, visual_model = buildModelsFromUrdf(filename, package_dirs, root_joint, verbose, meshLoader)
  File "~/.local/lib/python3.8/site-packages/cmeel.prefix/lib/python3.8/site-packages/pinocchio/shortcuts.py", line 45, in buildModelsFromUrdf
    geom_model = pin.buildGeomFromUrdf(model, filename, geometry_type, package_dirs = package_dirs)
ValueError: Mesh meshes/mini_body.obj could not be found.
```

This seems related to https://github.com/stack-of-tasks/pinocchio/issues/1747. Perhaps ``"meshes/mini_body.obj"`` is not considered a relative path in [parsers/utils.hpp](https://github.com/stack-of-tasks/pinocchio/blob/c0e7066c86018516abd08332966bc592fb68b0fb/src/parsers/utils.hpp#L103)?

Checks:

- I've checked that ``package_dirs[0] + "meshes/mini_body.obj`` exists on my filesystem
- Manually replacing all instances of ``meshes/`` by ``./meshes/`` in the URDF, the description loads properly

**Comment by fabinsch** [comment]
Hello, I think It should be fine now, on PyPI you have [Pinocchio v2.6.12](https://pypi.org/project/pin/2.6.12/). You can test if it works in your setup and let me know.
